### ISSUE TITLE
Adapt automation that uses the allocator

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-virtual-machines#207]
# Description

Due to the changes requested in [issue #2079](https://github.com/wazuh/wazuh-automation/issues/2079), modifications were made to the inventory generated by the Allocator.
The output format of `inventory.yaml` was modified to be in Ansible format.

Previous format:

```
ansible_connection:ssh
ansible_host: ec2-34-204-85-128.compute-1.amazonaws.com
ansible_port: 2200
ansible_ssh_common_args: -o StrictHostKeyChecking=no
ansible_ssh_private_key_file: /tmp/wazuh-devops-testing-machines/wia-155/wia-155-23-01-2025-19-39
ansible_user: ubuntu
```

New format:

```
all:
  hosts:
    i-0296704b894b571b5:
      ansible_connection: ssh
      ansible_host: ec2-107-21-70-81.compute-1.amazonaws.com
      ansible_port: 2200
      ansible_ssh_common_args: -o StrictHostKeyChecking=no
      ansible_ssh_private_key_file: /tmp/wazuh-qa/automation-2036-ubuntu-22.04-691/automation-2036-ubuntu-22.04-key-7074
      ansible_user: ubuntu
```

This format is valid to be executed directly with an ansible playbook. For more detailed examples see this [comment](https://github.com/wazuh/wazuh-automation/issues/2079#issuecomment-2649200692)

Review any automation that uses the inventory of Allocator to adapt them to the new format.

The objective of this issue is to modify the automation that utilizes the allocator; these modifications will take effect from version 4.12.0 onwards.
For testing you can use the branches:
- Based on main: enhancement/2079-adapt-allocator-to-generate-ansible-inventory-to-master
- Based on 4.12.0: enhancement/2079-adapt-allocator-to-generate-ansible-inventory

# Approved by

DRI name:
